<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>PngtoWebp</AssemblyName>
    <RootNamespace>PngtoWebp.Gui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PngtoWebp.Core\PngtoWebp.Core.csproj" />
  </ItemGroup>

</Project>
